# Generated by Django 5.1.1 on 2024-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField()),
                ('binary_field', models.BinaryField()),
            ],
        ),
    ]
